### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by Perflyst** [sriharshaarangi/BatteryChargeLimit#103]
How I can open it in Android Studio for editing and debugging?
I don't have the `keystore.properties` file which is needed in [build.grade#L5](https://github.com/sriharshaarangi/BatteryChargeLimit/blob/master/app/build.gradle#L5).

If it is not possible to open this project in Android Studio, which editor I should use?

**Comment by milux** [comment]
You have to create a keystore or switch to the debug build.
The keystore contains the keys for signing of the release APK. We can't share those for rather obvious reasons.
