### ISSUE TITLE
Status information overlaps

### ISSUE THREAD

**Issue by Perflyst** [sriharshaarangi/BatteryChargeLimit#105]
The voltage and temperature overslaps a little bit. Is this only on my device or have others this issue too?

**Phone Model:** Samsung Galaxy S6
**OS:** LineageOS14.1
**App Version:** F-Droid, 1.1.0 (22)
![image](https://user-images.githubusercontent.com/26308977/38252217-e094c28a-3753-11e8-9fc1-b854ef9c667f.png)

**Comment by sriharshaarangi** [comment]
7bfcf8b25ccf24a837f0ccda181e1489f3580845 fixes this
