### ISSUE TITLE
Can you please add support for Le Eco S3 x626

### ISSUE THREAD

**Issue by k-stantschev** [sriharshaarangi/BatteryChargeLimit#113]
Only white screen appearing when strarted. I don't know where to find the control file. Thanks in advance!

**Comment by sriharshaarangi** [comment]
Control files for several devices: https://github.com/sriharshaarangi/BatteryChargeLimit/blob/master/app/src/main/res/raw/control_files.json
You can use it as a starting point to search for a suitable control file.
Please see this for more info: https://forum.xda-developers.com/android/apps-games/root-battery-charge-limit-t3557002
Reopen this if you find a working control file.
