### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by waqasanwar94** [sriharshaarangi/BatteryChargeLimit#115]
Hello, @sriharshaarangi I want to contribute in "BatteryChargeLimit" so i want to design a new logo for "BatteryChargeLimit" and it's free.

I hope you like it. If you like it, I will send you to pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

Contact me on facebook for fast delivery 
https://www.facebook.com/waqasanwar68

**Comment by sriharshaarangi** [comment]
Thanks, but we like the current logo, and we are not looking for a new one right now.
