### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by tacticalDevC** [sriharshaarangi/BatteryChargeLimit#118]
In a nutshell:

If the phone is locked and I unplug the cable the notification persists.

If the phone is unlocked it vanishes.

**Comment by milux** [comment]
Funny, but if nobody else observes this behavior on another device, then it's most likely something like an OEM-specific "power save functionality" or some weird software stuff that causes this strange behavior.
I think that there is nothing we can do to fix that on our end, sorry. :(
