### ISSUE TITLE
Works fine on J5 stock but not on S4 Mini LineageOS

### ISSUE THREAD

**Issue by Schroef-77** [sriharshaarangi/BatteryChargeLimit#125]
First of all I would like to thank you for this feature I have been waiting for since years.

As soon as I discovered this app I installed it on both my devices mentioned in the titel.

The Samsung J5 (2017) runs stock rom rooted. The app runs as exspected.

On the S4 Mini I9195 the app starts ok but once the  max is hit it continues charging after it stopped for a minute or so  and doesnt respect the max limit anymore. This phone runs LineageOS 14.1.

**Comment by sriharshaarangi** [comment]
I have an S4 mini i9192, and it works well on stock ROM with _batt_slat_mode_ control file. You can check the control file in  Settings > Set Control File, and see if any of those options work. It is ROM specific incompatibility, and so there is nothing we can do if none of them works.
