### ISSUE TITLE
Feature request: remember and restore last state of charge

### ISSUE THREAD

**Issue by DmitriK** [sriharshaarangi/BatteryChargeLimit#135]
I'm in a situation where my phone is on a charger most of the time, but I'll often take it with me for a short amount of time (I don't like leaving it around unattended), unplugging it and shortly after plugging it back in. When this happens, the battery always charges back to my configured maximum. This results in short cycles, which from what I've read is not that great for the battery.

The feature request is that when unplugged, the app stores whether it was previously charging to the max, or maintaining charge, and keep that state when plugged in again (assuming it hasn't dipped below the minimum). Possibly add a way to clear the file in case someone knows they'll need the capacity and want to charge back to the max capacity.

Also, thanks for this app. I've gone through 3 swollen batteries before I realized my habits were ruining the battery, and this app makes it so much easier to prolong life without having to manually watch and juggle charge%.

**Comment by milux** [comment]
Although not identical, there is a pull request for a similar feature here:
https://github.com/sriharshaarangi/BatteryChargeLimit/pull/83
The idea is to only start charging when the device is below the **lower** threshold.
This should be sufficient for that as well, so I'm closing that one here.
