### ISSUE TITLE
Xiaomi Redmi 4A

### ISSUE THREAD

**Issue by zephyr88** [sriharshaarangi/BatteryChargeLimit#138]
The app works fine in stopping the charge.  Notification is off, however, when it reaches the limit, it stops the charge, but it keeps on giving out a notification sound without stopping, unless I pull the plug off.

Android Version is Nougat, ROM is official Xiaomi MIUI 10 developer rom

**Comment by milux** [comment]
Then this is a notification sound from the device itself, correct?
I'm not sure whether we can do anything about that...

**Comment by milux** [comment]
Closed since no new information, and bug being entirely ROM-specific.
