### ISSUE TITLE
Incompatible with powerbanks! 

### ISSUE THREAD

**Issue by donpapadee** [sriharshaarangi/BatteryChargeLimit#141]
The app doesn't work well with powerbanks as it keeps on crashing repeatedly until the app crashes & the battery eventually charges to 100%. 
I've tried it on two different brands but same results! 
Please fix, thanks ☺
[Oneplus one]

**Comment by milux** [comment]
I use two devices with a multitude of power banks and never experienced issues.
This seems to be a rare corner-case problem of your device. Sorry, but I believe that we're neither able, nor do we have the capacity to examine that issue.
