### ISSUE TITLE
Xperia XZs Charge limit reached, and stayed at the same level

### ISSUE THREAD

**Issue by chanwilson01** [sriharshaarangi/BatteryChargeLimit#149]
Hi, I'm new to GitHub just trying to find a solution to my problem.
I've use BCL on ,y Nexus 4 and Moto X with no problem. App works fine. Charge to limit, discharge to minimum then charge again.
However, with my XZs, stock rom only unlocked bootloader and rooted, the phone charges to limit (80%),
then it "stopped charging" app shows discharging, the "charge" icon is gone. 
But the phone just holds the charge. doesn't discharge at all even I turn up brightness to max and using gps navigation.
I've tried different Control files, 'charging_enabled' and 'status'. Non of them worked

My phone is Xperia XZs G8232
Android 8.0.0
Build 41.3.A.2.213
Kernel 3.18.66-perf-g768a6d20dc23

Hope this help. Thanks in advance :)

**Comment by sriharshaarangi** [comment]
That's a good thing and you are one of the fortunate ones! Holding up charge is better than discharging and charging, and not all phones support it.
