### ISSUE TITLE
LG V30 & V30+ (works but in-case you want model-specific entries)

### ISSUE THREAD

**Issue by solidsneak** [sriharshaarangi/BatteryChargeLimit#150]
The LG V30 and LG V30+ are identical phones aside from the internal storage on the V30 being 64 GB and on the V30+ it's 128 GB. This should be applicable to both.

**file:** "/sys/class/power_supply/battery/battery_charging_enabled"
**suggestion for details:** "LG V30/+"
**chargeOn:** "1"
**chargeOff:** "0"

Please let me know if you need more information. This does work with the V30+ as installed, by default but I'm not sure if you want to include specific phones for any reason or not.

**Comment by milux** [comment]
This file is already available, tagged with "Nexus" (the phone were it was observed first).
I don't see the point of this request. If I'm mistaken, please reply to me and I will reopen.

**Comment by solidsneak** [comment]
The point was in the parenthesis in the title.

**Comment by milux** [comment]
@solidsneak Good point, thank you. As some control files work for a large variety of devices, we usually stick to the first device where it was observed to work, but maybe this will be changed in the future.
