### ISSUE TITLE
Blackview 9600 Pro

### ISSUE THREAD

**Issue by tecs-ottawa** [sriharshaarangi/BatteryChargeLimit#152]
I've tried every file in my phones OS I could find that might be the right one, but none of them work. I tried "status" and "present" in the "/sys/class/power_supply/battery/" directory and when I checked the contents of those files while they were supposed to be changed, they weren't. The app does have root access, and I've made sure those files can be modified with the permissions they have, but they just stay whatever they normally are no matter what i set in BCL. Are these the wrong files, or is something else going on? If someone could help me identify the right files or get these working that would be great and I can provide any info needed!
Thanks :)

**Comment by milux** [comment]
This is an invalid request, as such request pollute the issue tracker. If you're looking for community support for control file hunting, please use the XDA thread.
Please open a new issue for your model in case you find a working control file.
