### ISSUE TITLE
battery temperature limit?

### ISSUE THREAD

**Issue by divinity76** [sriharshaarangi/BatteryChargeLimit#154]
stop charging when battery temperature above X, and resume charging when battery temperature goes below Y?

i got a phone with Qualcomm's Quick Charge 3.0, and the temp goes all the way to 48c (118.4f) (or more?) when charging, a google search suggest the safe charging temperature for li-ion batteries are 0-45c (32-113f), meaning the battery gets too hot while QuickCharge'ing.. since i don't want to damage the battery by overheating, i'm now looking for a way to turn off charging once the battery temperature gets too hot, and resume charging once it cools down..

has been requested before in #23

**Comment by sriharshaarangi** [comment]
Yeah, we will track the item in #23
