### ISSUE TITLE
How to prevent background processes from being killed

### ISSUE THREAD

**Issue by zixijian** [sriharshaarangi/BatteryChargeLimit#155]
as title，

**Comment by hmarceau** [comment]
I have a Pixel 1. The program does work with me. But the battery continues to charge overnight. I also believe that the background process is being killed after some time. Battery optimization is not enabled for this app. Would you have a workaround?
Thanks!

**Comment by zixijian** [comment]
turnoff lowmemorykiller is helpful,

>echo 0,0,0,0,0,0 > /sys/module/lowmemkiller/parameters/minfree
