### ISSUE TITLE
Can you please add support for HTC U11+

### ISSUE THREAD

**Issue by nicodelius666** [sriharshaarangi/BatteryChargeLimit#156]
Hi, I have more than one ctrl file. Can you tell me which to choose?

They are in /sys/class/power_supply/battery:
-charging_enabled;
-charger_control;
battery_charging_enabled.

All of these are in this folder.
I'm on Oreo.
Thanks!

**Comment by sriharshaarangi** [comment]
All these control files are present in the app, so try each of them and see which one works :)
