### ISSUE TITLE
Min limit is not working if charger disconnected and reconnected

### ISSUE THREAD

**Issue by knreddypc** [sriharshaarangi/BatteryChargeLimit#157]
Dear sir,
The mobile is Redmi note 4x mido , MIUI 8, 9, 10 or Lineage OS 15.0 or 15.1

The battery charge limit is stopping  thr charger at max limit and if the mobile is bing discharged while connected to the charger  by using the mobile , battery charge limit is waiting  till the min limit is reached but if mobile is removed and reconnected it is not waiting till the lower limit is reached i.e the lower limit is not working as expected with any of control file
Regards

**Comment by sriharshaarangi** [comment]
It's a known issue being tracked at #42
