### ISSUE TITLE
Автор приложения станет ли выпускать аналог программы для Windows/Linux (для ноутбуков)

### ISSUE THREAD

**Issue by Pritcha** [sriharshaarangi/BatteryChargeLimit#160]
Уважаемый Автор, хочу узнать будете ли Вы разрабатывать аналог BatteryChargeLimit для ноутбуков, под управлением ОС Windows и Linux? На всех моих устройствах уже установлено Ваше приложение, и отлично себя зарекомендовало, теперь хочу использовать и на ноутбуках..,

Спасибо за Вашу работу ;-))
nash-urist@ya.ru

-----------------------------
переведено при помощи: http://deeptrantci3pydq.onion/

Dear Author, I want to know whether You develop a counterpart BatteryChargeLimit for laptops running Windows and Linux? On all of my devices already installed Your app, and a well-established, now I want to use on laptops.., 

Thank you for Your work ;-))

**Comment by milux** [comment]
Nope, that's technically completely different, and we have no plans for anything like this.
