### ISSUE TITLE
Feature request: enable/disable charging

### ISSUE THREAD

**Issue by ps-spark** [sriharshaarangi/BatteryChargeLimit#168]
Hi Developers,

thank you very much for your great work. I really appreciate. Could you add the feature to completely disable charging independent from battery status? It would be a great feature for the drone-flying community, because the drone`s controller is connected to the phone and thus it will be automatically charged draining the controller's battery + making the phone hot.

I would gladly donate for this feature :)

Thank you in advance!

Kind regards,
ps-spark

**Comment by milux** [comment]
Does already exist in recent beta version, check XDA for details to join the respective Telegram beta tester group. Closing.
