### ISSUE TITLE
"Recharge below" isn't respected, but "Limit charging to" functions properly. OnePlus 7 Pro GM1917 (rooted)

### ISSUE THREAD

**Issue by patrickhgb** [sriharshaarangi/BatteryChargeLimit#170]
Using default configuration file, the "recharge below" is not respected. Phone will continue to charge as long as it's under the maximum charge limit.

Any idea why it's half broken?

Also we should probably update the APK, seeing as there's updates to the source files beyond 1.1.1's release date?

**Comment by patrickhgb** [comment]
Edited main post since I accidentally pressed enter.

**Comment by ayushpsc** [comment]
I have this same issue on Redmi Note 7. Were you able to solve this?
