### ISSUE TITLE
Is there a list of devices this app is compatible with?

### ISSUE THREAD

**Issue by danwat1234** [sriharshaarangi/BatteryChargeLimit#174]
Is there a list of devices this app is compatible with? does this app support the Motorola Moto Z2 Force?

**Comment by TiraelSedai** [comment]
Should be working with every rooted device. If it doesn't work with yours, report an issue.

**Comment by milux** [comment]
> Should be working with every rooted device. If it doesn't work with yours, report an issue.

Not entirely correct. Should be working **with every rooted Android OS featuring a well-known control file**.

Edit: @danwat1234 to answer your question: No, that's impossible. There are many thousand devices out there, we would not be able to maintain such a list.
