### ISSUE TITLE
Need help, not working on Realme X.

### ISSUE THREAD

**Issue by JoeNirvana** [sriharshaarangi/BatteryChargeLimit#181]
Probably because it use OPPO VOOC charge, any solution?
Kernal source is here:[https://github.com/realme-kernel-opensource/realmeX-kernel-source](url)

**Comment by sk33wiff** [comment]
Same here, realme 5 pro

**Comment by milux** [comment]
> Probably because it use OPPO VOOC charge, any solution?
> Kernal source is here:[https://github.com/realme-kernel-opensource/realmeX-kernel-source](url)

Maybe, but BCL (and most similar apps/scripts, I believe) are just changing the content of files that control the charging logic, so nothing we can do here. You can check whether ACC is doing better on your device, maybe there is some control file BCL doesn't know of...
