### ISSUE TITLE
Please support to Android GINGERBREAD Samsung GT-S6102

### ISSUE THREAD

**Issue by sobirins** [sriharshaarangi/BatteryChargeLimit#192]
Tidak bisa di instal sama sekali, 
Tolong buat untuk support di android gingerbread
Dan jika tidak bisa, apa ada cara lain untuk membatasi mengisi baterai secara manual

**Comment by milux** [comment]
Android Gingerbread is way too old to receive support.
Even if it was technically possible (it isn't), we wouldn't have the time and resources to backport to such ancient Android releases.
Regarding manual charging control, please see the XDA Thread, technical backgrounds are discussed there. Basically, you will have to overwrite a certain file with root privileges, typically using some terminal emulator app.
