### ISSUE TITLE
Do not work with Amazon Fire HD 10 2019, OS version 7.3.1.0

### ISSUE THREAD

**Issue by kevinwish** [sriharshaarangi/BatteryChargeLimit#200]
This app does not stop the charging of the Fire HD tablet running 7.3.1.0. Device is rooted.

**Comment by gokul1630** [comment]
app won't work without root🙄

**Comment by kevinwish** [comment]
> 
> 
> app won't work without root🙄
fire OS 7.3.1.0 is rooted
