### ISSUE TITLE
Support for Nintendo Switch with Android (Foster and Foster tab)

### ISSUE THREAD

**Issue by chiveta** [sriharshaarangi/BatteryChargeLimit#203]
Here source; https://gitlab.com/switchroot/android

from what I've been reading from the compiled android source it uses max170xx, but what they update the most from the source is this, I'm sorry I don't understand much of this.

https://gitlab.com/switchroot/kernel/l4t-kernel-4.9/-/blob/lineage-17.1/drivers/power/supply/max17042_battery.c

**Comment by milux** [comment]
We need a control file here for adding support.
Doing research about the functionality used in ROMs is beyond scope for this project.
