### ISSUE TITLE
Tasker and Battery Charge Limit

### ISSUE THREAD

**Issue by Shadeclan** [sriharshaarangi/BatteryChargeLimit#205]
Is it possible to control Battery Charge Limit with Tasker?  If so, how would I do it?  In Tasker Tasks (Launch App), I can see the "LimitChangeActivity" but I don't know what data to send it to get it to activate / deactivate.  I can also see the "activities.MainActivity".

**Comment by kaoneko** [comment]
You could just recreate the functionality of Battery Charge Limit in Tasker. Make a profile that activates when charging and charge is above the threshold. Enter task writes the "disabled" value to the control file (by executing a shell command as root, something like `echo 0 > controlfile`).

**Comment by Shadeclan** [comment]
I looked at that and thought about doing that but in the end, I decided to uninstall Tasker altogether.  I found that profiles involving app monitoring drained my profile.  I found I could do what I wanted with [Autoroid](https://play.google.com/store/apps/details?id=com.soosu.autoroid) with a lot less battery drain.  As far as Battery Charge Limit is concerned, I rethought how and when I charge the phone and abandoned my Tasker idea.

**Comment by milux** [comment]
> Is it possible to control Battery Charge Limit with Tasker? If so, how would I do it? In Tasker Tasks (Launch App), I can see the "LimitChangeActivity" but I don't know what data to send it to get it to activate / deactivate. I can also see the "activities.MainActivity".

Yes, you can, absolutely!
I recommend using a Broadcast for this, not the Intent/Activity way.
See the very README.md of this repository for directions! ;)

**Comment by milux** [comment]
BTW: I'm controlling the limit via an Automate Flow.
https://mega.nz/file/AtdzCCDY#KH-pvO_TrtpiewfFsW8doZ-wsql7RSXrrpC-04OUrS0
