### ISSUE TITLE
Doesn't work with Huawei Y360-U31

### ISSUE THREAD

**Issue by Mike-0815** [sriharshaarangi/BatteryChargeLimit#207]
Hello !

Installed BatteryChargeLimit, but unfortunately it doesn't work. It installs fine and I chose the Motorola Defy+ (MB526) control file.

As I use this phone nearly permanently on the power-cable, I choosed to hold a range of 50-55% battery level and started the service. When the battery level reached 55%, the app told me to hold 50-55% battery level. But the battery will be continously charged without limitations, like without the app installed.

Any help welcome, thanks in advance,
Kind regards
Mike

**Comment by kagar4** [comment]
Try to use magisk module called **input power control**, May be work on your device
or you can type in termux after instal IPControl module
`su -c sh /data/adb/modules/IPControl/debug.sh`
to find control file on your device, and you can use it with battery charge limit

**Comment by milux** [comment]
There is no guarantee whatsoever that BCL works with any device, or even specific ROM version.
