### ISSUE TITLE
not working on my samsung gt-s5830

### ISSUE THREAD

**Issue by egoruh** [sriharshaarangi/BatteryChargeLimit#21]
not working on my samsung gt-s5830 (cyanogen mod 11, android 4.4.4)

**Comment by milux** [comment]
Not enough information to take action.
Which control file is selected? How exactly is it "not working"?

**Comment by egoruh** [comment]
At startup, writes that the device is not yet supported.

**Comment by milux** [comment]
This is not a bug. If you want so see your device supported, please provide information about the control files you found on your device, see the FAQ for details.
Closed due to invalidity.
