### ISSUE TITLE
Mojave support

### ISSUE THREAD

**Issue by yabo-boye** [sriharshaarangi/BatteryChargeLimit#215]
Is there any way this can be supported on Mojave, even with limited functionality? I upgraded to Catalina just for this, unfortunately it has a few very annoying problems that are killing my workflow (especially Bluetooth issues). I would love some version of this to work in Mojave, and I would contribute to make it happen.

Thank you for your amazing work!

**Comment by milux** [comment]
Sorry, I don't get it... we're building an Android application here, you're talking about MacOS versions... Please elaborate a little more, because I honestly have no idea what you are talking about, sorry. :sweat_smile:

**Comment by yabo-boye** [comment]
oh shit. i got the wrong github, lol
i was meaning to post this in the forum that has a similar app for macos.
sorry for the confusion !

**Comment by thejohnha** [comment]
@yabo-boye Now I'm curious - which is the other repo for macOS? thanks!

**Comment by yabo-boye** [comment]
https://github.com/davidwernhart/AlDente

great app

**Comment by thejohnha** [comment]
thanks @yabo-boye it's awesome!!! Now if I could just get this repo working on my android phone...
