### ISSUE TITLE
Poco x3 pro, doesn't detect charger disconnect

### ISSUE THREAD

**Issue by pulsarice** [sriharshaarangi/BatteryChargeLimit#216]
First, the default control file is not working. I had to switch to input_suspend.
Now when the charge reaches the threshold, charging is stopped. But after disconnecting the charger, it still shows "maintaining ..." notification and I have to manually select disable to close the notification and reset the battery stats.

These files are in this path 
`/sys/devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply`
When charge level reached and charger is connected [battery_maintain.zip](https://github.com/sriharshaarangi/BatteryChargeLimit/files/6668682/battery_maintain.zip)

After disconnecting the charger [charger_disconnect.zip](https://github.com/sriharshaarangi/BatteryChargeLimit/files/6668681/charger_disconnect.zip)

**Comment by pulsarice** [comment]
I attached two files to the first post

**Comment by spaetz** [comment]
Hi, I am just trying /sys/class/qcom-battery/restrict_chg 0 1
and it could actually work well. Will report if it does.
