### ISSUE TITLE
App Denied Root Access or Device is Not Rooted

### ISSUE THREAD

**Issue by MattyHeath** [sriharshaarangi/BatteryChargeLimit#218]
Hi. I've just installed the app and I keep getting this message. My phone is plugged into the mains, and when I go into permissions on phone for the app, I can't find anything to allow. 

I was wondering if you could help? Thanks

**Comment by milux** [comment]
It is exactly what it says. This app requires a **rooted**, supported phone. (As all such Apps do btw., unless this functionality is part of the ROM itself.)
