### ISSUE TITLE
Battery stops charging but current still drawing.

### ISSUE THREAD

**Issue by alpha7504** [sriharshaarangi/BatteryChargeLimit#220]
Hello,

Using note 7 pro with pe+ 11 rom. BCL seems to be working to stop the charging but i see with accu battery app that, current is still being drawn from the charger. Confirmed with multiple apps all says the phone is discharging while 1500+ mAh being drawn from charger. So the battery percent remains at 80%, but internally the phone is still charging. And it's messing my battery calibration. 

In my other phone the current draw stops once charging stops..

**Comment by milux** [comment]
You have to try another control file, maybe it does not work for your ROM at all.
Nothing we can do here to improve situation.
