### ISSUE TITLE
Doesn't stop charging my Fairphone FP1

### ISSUE THREAD

**Issue by darsie** [sriharshaarangi/BatteryChargeLimit#221]
Using Android 4.2.2, the highest available version.

**Comment by thibaultmol** [comment]
Is this a fairphone 3 or 4?

**Comment by milux** [comment]
Without further information, nothing we can do on our side here.
My FP4 works perfect.

**Comment by darsie** [comment]
Fairphone Model FP1, FIRST EDITION

**Comment by milux** [comment]
There comes a time where even a Fairphone lifecycle ends. :wink: 
Android 4.2.2. is acient and insecure.
If you find a working control file, we can still add it, but from a security perspective, it's time for an update (hardware-wise) for sure.
