### ISSUE TITLE
Unexpected behavior in moto g5s plus

### ISSUE THREAD

**Issue by Aditya-R-K** [sriharshaarangi/BatteryChargeLimit#223]
After setting limit of 85% it stops at 75 or 74% and after uninstalling the app, phone charge up to 75% only.

**Comment by milux** [comment]
Some vendors implement such behavior intentionally. I know this from `store_mode` with my SM-P605 (Note 10.1 2014).
Disabling BCL and fully rebooting Android should restore old behavior.
