### ISSUE TITLE
Problem with honor 9 lite

### ISSUE THREAD

**Issue by davidaudi** [sriharshaarangi/BatteryChargeLimit#225]
Hi, in the past I have used this app on "lg g3s" and it worked perfectly, the battery regularly did the charge / discharge cycles in the established range.  Now I need to run the app on "honor 9 lite", I rooted the device and installed the app but unlike the "lg g3s" I can't get it to work well.  If I set the maximum value to 80, the app loads the device up to 80 and does not go beyond, the problem is that it does not start the download process but constantly keeps the level at 80%, the app tells me that it is being discharged but in reality the phone system tells me that it is charging ... in fact the battery charge level remains constant at 80. I kindly ask for help to solve the problem.

**Comment by milux** [comment]
This is not a problem at all. It means that only charging is disabled, and the phone is directly powered by USB. Other people would be happy if their devices supported this behavior.
