### ISSUE TITLE
Pixel 6 rooted do not stop automatic

### ISSUE THREAD

**Issue by lavoie005** [sriharshaarangi/BatteryChargeLimit#228]
Hi, i have rooted pixel 6 and the auto stop charging do not work on my phone

Pixel 6
Android 12
Version Number : SD1A.210817.036

**Comment by thejohnha** [comment]
I don't know the methodology of how to figure out what to set, but I tried the settings that worked for my Pixel 4a and they did not work. The Pixel 4a's settings I used were:

Turn ON `Configurable CTRL File Data`
Click `Configure Control Data`
Set path to desired file:
/sys/kernel/debug/google_charger/input_suspend
Enabled value: 0
Disabled value: 1
Uncheck "Enforce Charge Limit"
Check "Always Write CTRL File"

**Comment by tgice** [comment]
The default CTRL file of:

`Motorola Defy+ (MB526)`

also does not work for me.  It'd be great if anyone has figured this out yet and could post what to do!

I'm on build SQ1D.220105.007
