### ISSUE TITLE
feature request: close app notification when charger is disconnected.

### ISSUE THREAD

**Issue by rezad1393** [sriharshaarangi/BatteryChargeLimit#232]
feature request: close app notification when charger is disconnected.

it is a bit annoying that use has to click disable the service even after disconnecting the charger.

**Comment by milux** [comment]
For certain control files (those that only disable charging and not the whole power supply), this behavior is already exactly that.
For the other control files, this is not possible. Once the power supply is disabled, there is no way to detect the absence of the power supply, unless charging is re-enabled.
Therefore closing this issue.
