### ISSUE TITLE
Charging connection and disconnection detection

### ISSUE THREAD

**Issue by krzbor** [sriharshaarangi/BatteryChargeLimit#239]
I have my Galaxy Tab 2 connected to power all the time. Charging is cut off for a short while and resumed when the PIR sensor detects movement. This operation causes the screen to light up. This works very well, but after a few years of fully charging the battery in the tablet swelled up and I had to replace it. I installed ROOT and uploaded BatteryChargeLimit to save battery. In general, it works very well (guards the limits), unfortunately, the key functionality for me does not work - momentary disconnection of charging and its restoration does not wake up the tablet. Is it possible to add this functionality? So, regardless of the charge level, if the tablet detects the connection of the charger, the screen simply lights up.

**Comment by milux** [comment]
This is ROM-specific and totally out of scope for this application.
I would recommend rolling a wakeup mechanism with Tasker or Automate.
