### ISSUE TITLE
Add support for Samsung Galaxy Note 10.1 (2012)

### ISSUE THREAD

**Issue by oroboros** [sriharshaarangi/BatteryChargeLimit#27]
The 2014 Note 10.1 is supported. 

The GT-N8013 is the 2012 version, and it shows it is not supported.

**Comment by milux** [comment]
This is still not helpful, unless you want to give me your device for experiments. ^^
Please provide information when you find a file that controls battery/charging behavior.
> Closed.

**Comment by yakov116** [comment]
How do we find the file?

**Comment by milux** [comment]
Please read the **whole OP on XDA** and tell me if you still don't know the answer.
