### ISSUE TITLE
Add Support for Xiaomi Mi6 - I found a proper file to enable/disable charging

### ISSUE THREAD

**Issue by Shackmir** [sriharshaarangi/BatteryChargeLimit#29]
I found a right file which works for Mi6 on stock Android 7.1.1 (MiUi 9)
by editing this file

"file": "//sys/class/power_supply/battery/input_suspend",
"label": "input_suspend",
"details": "Xiaomi Mi6",
"chargeOn": "0",
"chargeOff": "1",

"0" allow charging and "1" disables charging
I tested it and works without  any problem, please add support for Mi6 ASAP. Thanks

**Comment by milux** [comment]
Please check out version 1.0.2 and report if it's working.

**Comment by Shackmir** [comment]
It works. Disables and enables charging automatically. App crashed few times but I whitelisted it in battery saving settings and now it works flawlessly. Thank you.

**Comment by Shackmir** [comment]
I found files where charging current can be modified. Is this enabled in this app on other devices? I can provide directory of this file.

**Comment by milux** [comment]
Thanks.
No, there isn't any feature like this yet.
If you have actual experimental results about software-define changes of charging current, please comment at https://github.com/sriharshaarangi/BatteryChargeLimit/issues/23

**Comment by Shackmir** [comment]
Unfortunately wiping battery stats on Xiaomi mi6 doesn't work.

**Comment by milux** [comment]
That's not related to the control file, please open a new issue for this.
