### ISSUE TITLE
Shield Tablet random crash after unplugging

### ISSUE THREAD

**Issue by bluegizmo83** [sriharshaarangi/BatteryChargeLimit#33]
I received a random crash at 17:29 today after unplugging power cable. Attached is an unfiltered logcat. If this is another weird crash like that crash i had at first run after installing the app this morning, don't worry about it, just close the issue. I'm going to uninstall this app and wait to test again until I get my system straightened out from that bad Titanium Backup restore I did a while back. I'm not really helping the situation here by continuing to test with a known system issue on my end. Thanks for your work on this app and adding experimental Shield Tablet support though! I appreciate it.

[2017-08-16-17-34-48.txt](https://github.com/sriharshaarangi/BatteryChargeLimit/files/1229774/2017-08-16-17-34-48.txt)

**Comment by milux** [comment]
I think I fixed it. However, a "normal" user won't encounter it normally, because it only occurs in combination with the cycling problem you described in the other post.
I will therefore close this issue, let's focus on the cycling, that's the real problem.

**Comment by milux** [comment]
You can find a corrected experimental build here:
https://www.androidfilehost.com/?fid=961840155545589430
This one shouldn't crash anymore when the power plug is removed. If it still does, I screwed up. 😉
