### ISSUE TITLE
Support of maguro/tuna

### ISSUE THREAD

**Issue by guest4711** [sriharshaarangi/BatteryChargeLimit#34]
My GN (maguro) running DU 11.7 has /sys/class/power_supply/battery/charge_enabled with values=0|1

Can you please add it?

**Comment by milux** [comment]
I assume "0" disables charging and "1" resumes charging?

**Comment by guest4711** [comment]
Yes, you are right. Sorry for not telling it before.

**Comment by milux** [comment]
Will be added in the upcoming version.

**Comment by guest4711** [comment]
Thank you so much, just testing. Seems to work fine...

**Comment by milux** [comment]
Could you please report back after testing, so I can remove the experimental-Flag?

**Comment by milux** [comment]
A assume that means yes. ^^
