### ISSUE TITLE
Battery stats reset doesn't work on Galaxy S3/4.3

### ISSUE THREAD

**Issue by vovodroid** [sriharshaarangi/BatteryChargeLimit#36]
Actually that's the issue.
See also discussion https://forum.xda-developers.com/android/apps-games/root-battery-charge-limit-t3557002/post73513352#post73513352

**Comment by milux** [comment]
As bluegizmo83 pointed out correctly, you would need to find a command or API that can do what we do when executing `dumpsys batterystats --reset`.
I don't own any device with Android < 5.1.1, so I won't help you with this.
But if you find something, please let me know, and I will reopen this immediately.
