### ISSUE TITLE
Support for mipad 2

### ISSUE THREAD

**Issue by iStelmuhov** [sriharshaarangi/BatteryChargeLimit#41]
Control file for mipad 2:  /sys/class/power_supply/bq2589x_charger/enable_charging

**Comment by milux** [comment]
More details about contents of that file please?
0 to disable charging and 1 to re-enable? Or "disabled" and "enabled"? Or something completely different? :wink:

**Comment by iStelmuhov** [comment]
Yes, "1" for enable, "0" for disable.
