### ISSUE TITLE
LG G5, palese give some love :*

### ISSUE THREAD

**Issue by xxskorpion88xx** [sriharshaarangi/BatteryChargeLimit#42]
Hi,

Im an LG G5 owner. I please ask you to supporto G5 because in my case this app would have saved my phone from bending the screen.. Yes read right.

(Little story spoiler)
LG G5 is unibody metal with sleeve battery (no back cover)..so a "keep growing battery" find his "locus minoris resistentiae"(alias avere could grow with minor pressure) in upper parte exactly below IPS frame.

As in my case you won't notice any bulging from back part but when happen, you recognize surfing on web page in white background some circular strain In various colour where the pressure hit the screen, like discolorations.

Further investigations made me conscious that leaving the phone face down on table gave the phone a " ship form".. yes my gorilla glass 4 was bendedand my battery stucked inside without possibility to remove it.

 It also 1 and half months in LG assistant service (they took pieces from Singapore and take a while to ship in Italy)
(/finish spoiler)

So cross fingers for all LG G5 owners and a warning to them.. Sleeve the battery from inside at least once a week to recognize the first signs of bulging, or hug this app ;)

**Comment by milux** [comment]
Sad for your device... 😕 
I don't see any information about control files and have no access to a LG test device.
So... give me sufficient information, and I will implement support.
Meanwhile: **closed.**
