### ISSUE TITLE
Nexus 6 - Cannot charge

### ISSUE THREAD

**Issue by CarlB86** [sriharshaarangi/BatteryChargeLimit#48]
Nexus 6 (shamu)
Magisk systemless root using Magisk Manager

Charge limit worked perfectly until the max cutoff. After falling below the minimum, it is continuing to drain. Phone will not charge even after disabling Battery Charge Limit or even uninstalling the application.

Currently /sys/class/power_supply/battery/charging_enabled is set to 1 and still won't charge.

(disabling and re-booting restores charging functionality)

**Comment by milux** [comment]
Whether a device is reacting properly to the CF changes depends on the implementation of the OEM.
There's nothing we can do to make this work if it doesn't, sorry. :(
Please try to use/find another control file that might do the job correctly. If you can't, then you're out of luck, sorry.
BTW: Some devices allow charging again when the percentage dropped below a certain threshold. 70 % is a typical value that has been observed by some users. You might wanna try if that's the case for you as well, and if you can live with that.
