### ISSUE TITLE
Bengali (Bangladesh) Translation!

### ISSUE THREAD

**Issue by AdroitAdorKhan** [sriharshaarangi/BatteryChargeLimit#50]
[BatteryChargeLimit.zip](https://github.com/sriharshaarangi/BatteryChargeLimit/files/1326594/BatteryChargeLimit.zip)
Bengali Translated String File is added below! :)

**Comment by milux** [comment]
Thanks, will add it asap!
Maybe you can do a pull request next time? That would make things more convenient for everyone.

**Comment by AdroitAdorKhan** [comment]
I'm sorry! I'm a noob here in GITHUB! :(

**Comment by milux** [comment]
@AdroitAdorKhan I did my very best to include your translation properly.
However, the whitespace in the XML file you provided was terribly screwed up, so there might me error in there... please report back when we release the next version.

**Comment by milux** [comment]
@AdroitAdorKhan Can you please check the translation in version 1.1.0?

**Comment by AdroitAdorKhan** [comment]
@milux Yes! I checked it, few strings are missing! And, I'm sorry, I used an app to translate on my android device, that might have made whitespace! Can you help me to find the exact string file to translate? :) I'll translate it again properly!

**Comment by sriharshaarangi** [comment]
@AdroitAdorKhan [this](https://github.com/sriharshaarangi/BatteryChargeLimit/blob/master/app/src/main/res/values/strings.xml) is the strings file in english, and [this](https://github.com/sriharshaarangi/BatteryChargeLimit/blob/master/app/src/main/res/values-bn-rBD/strings.xml) is the file that contains Bengali translation

**Comment by AdroitAdorKhan** [comment]
@sriharshaarangi I'm done changing the English Strings to Bengali! and, pulled a request! :)

**Comment by sriharshaarangi** [comment]
@AdroitAdorKhan  Thanks! But I don't see any pull request. Can you please verify and create a pull request again?

**Comment by AdroitAdorKhan** [comment]
@sriharshaarangi will you check this time, I haven't figured out all git stuffs yet! Sorry for the inconvenience!
