### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by northmendo** [sriharshaarangi/BatteryChargeLimit#52]
I would like to see a feature to have battery charge limiter be able to auto enable and disable a specific times. E.g. turn on in the am and of in the pm so the phone will charge fully overnight only.

**Comment by milux** [comment]
This is already possible via any automation app, using Broadcasts or Intents.
We do not intend to implement any more logic for this within the app directly.

**Comment by northmendo** [comment]
Where are the boadcasts/intents documented?

**Comment by milux** [comment]
Right here in the README.md of the project. And of course within the XDA OP, too.

**Comment by northmendo** [comment]
Of course it is. Sorry I missed that. Thanks for the app. I love it.
