### ISSUE TITLE
F-Droid listing should state that the app requires root

### ISSUE THREAD

**Issue by arschficken** [sriharshaarangi/BatteryChargeLimit#54]
I was wondering how the app managed to control charging without root. The answer is, it doesn't. But I shouldn't have to install the app just to discover that I can't use it.

Please clearly state this in the description, the way all the other root apps do.

**Comment by sm4rk0** [comment]
Consider it (half)done. Just needs to be merged:
https://gitlab.com/fdroid/fdroiddata/merge_requests/2573

**Comment by milux** [comment]
Thanks @sm4rk0 !
@arschficken I consider this issue resolved, will reopen in case of further related questions.
