### ISSUE TITLE
option to not display a permanent notification

### ISSUE THREAD

**Issue by jpggithub** [sriharshaarangi/BatteryChargeLimit#55]
Please add an option to not display the permanent status of the app in the notification aera.
In my opinion, the status is just useful for someone that is worried about this status ;-) If everything works fine, it's like another parameters of the phone and a permanent notification is not required anymore.

**Comment by milux** [comment]
You're wrong about the meaning of the notification.
It cannot be removed for the following simple reason:
Apps that do not display a permanent notification cannot run background services with high priority. The OS considers such background services "low priority" and kills them instantly when it thinks that it needs more RAM for whatever reason.
