### ISSUE TITLE
Limit set to 90%, stops charging at 70%

### ISSUE THREAD

**Issue by jordanade** [sriharshaarangi/BatteryChargeLimit#56]
Using superman ROM on a Samsung galaxy s7 sm-g930f. Tried both control files available to me (store_mode and batt_slate_mode) and didn't seem to make a difference.

Logs with suggested filter don't include anything at the moment it hits 70. But I can attach complete logs (is there any sensitive information I should edit out?)

**Comment by jordanade** [comment]
![screenshot_20171004-234923](https://user-images.githubusercontent.com/2799445/31210688-05c9b464-a962-11e7-9caa-527b82e1ccee.jpg)
![screenshot_20171004-235347](https://user-images.githubusercontent.com/2799445/31210691-0de263bc-a962-11e7-85d3-fc0bd5315dde.jpg)
![screenshot_20171004-235311](https://user-images.githubusercontent.com/2799445/31210693-11d3709c-a962-11e7-9fc4-f85f9712c2e4.jpg)

**Comment by jordanade** [comment]
To clarify, the CHARGE_FULL message appears right after I connect the charger, not when it hits 70%

**Comment by milux** [comment]
Let me guess... you're using the **store_mode** control file? 🙈 
There are plenty of Samsung devices that show the 70 % behavior when using store_mode... I'm getting tired of all the issues and posts about it - no offence!
Is there another control file that you can select in settings?

**Comment by jordanade** [comment]
Yes. I didn't realize I had to restart after changing the control file to batt_slate_mode. That fixed it. You may want to put a message to that effect in the UI.

**Comment by milux** [comment]
Wise words... I will consider doing something like that to warn users about the pros/cons of the store_mode control file. Thanks!
