### ISSUE TITLE
Control File for Lenovo is reversed by the OS

### ISSUE THREAD

**Issue by assafco** [sriharshaarangi/BatteryChargeLimit#59]
The control file for this tablet is /sys/class/power_supply/battery/present
I use this command to overwrite it: su -c echo 0 >> /sys/class/power_supply/battery/present
After changing this value to 0 the OS reverse it automatically back to 1. 
I tried also to edit the file with some text editor, the device is forced to restart after changes are saved.
The file is initially in read-only mode, but even changing the file mode to read-write doesn't also help.
Anyone has any idea how to deal with such situation??

**Comment by milux** [comment]
Dear @assafco, this is not the right place for a discussion about that, because it is not related to the development of BCL. Please use the XDA thread to discuss this issue and ask for help.
