### ISSUE TITLE
LeEco Le 1s Support!

### ISSUE THREAD

**Issue by AxelBlaz3** [sriharshaarangi/BatteryChargeLimit#67]
**Control file location:** 

/sys/devices/platform/mt-battery/disable_charger
1 = Charging disabled
0 = Charging enabled

**Testing**

/sys/devices/platform/mt-battery # echo 1 > disable_charger
/sys/class/power_supply/battery # cat status
Not charging

**Comment:**
Device won't charge anymore. The led charging light gets turned off and device stops charging.

/sys/devices/platform/mt-battery # echo 0 > disable_charger
/sys/class/power_supply/battery # cat status
Charging

**Comment:**
Device charges now.

**Comment by milux** [comment]
As you've already contributed a PR, I will close this.
Thank you!
