### ISSUE TITLE
Feature Request: An intent to enable/disable the entire limit/app

### ISSUE THREAD

**Issue by ApertureAndroid** [sriharshaarangi/BatteryChargeLimit#7]
Being able to change the limit via intent is pretty nice, but how about being able to completely disable or enable the limit?

**Comment by milux** [comment]
I think we could modify the intent processing such that a target level of "100" disables the service, while any other valid value will re-enable it. What do you think about this idea?

**Comment by ApertureAndroid** [comment]
That sounds perfectly reasonable, @milux. Good idea.

**Comment by ApertureAndroid** [comment]
Added in 0.10.0. Thanks!
