### ISSUE TITLE
Support Xiaomi mi note 3

### ISSUE THREAD

**Issue by Nobeernogman** [sriharshaarangi/BatteryChargeLimit#72]
Note 3 with magisk 14.0.
Control file: input_suspend (Xiaomi mi 6) 

Charger charge over the set limit of 80%

I also have a problemen with switching to another profile, i can't select another profile.

**Comment by milux** [comment]
If you can't select another control file, it's likely because the selected one is the only available one on your device. It it doesn't work, then your device is likely not supported by BCL, and there is nothing we could do about that.
**CLOSED**

**Comment by milux** [comment]
BTW: You can look for another - yet unknown - control file yourself. If you find something working, suggest it in a separate issue.
