### ISSUE TITLE
Please suport Xiaomi Mi A1

### ISSUE THREAD

**Issue by jochen24** [sriharshaarangi/BatteryChargeLimit#73]
None of the existing control files are working for Xiaomi Mi A1.
I found the following working control file. Please add it to the supported devices.

/sys/devices/soc/qpnp-smbcharger-18/power_supply/battery/battery_charging_enabled

**Comment by milux** [comment]
What flags cause the desired change? I assume those:
1 = charging on
0 = charging off
Is that correct?

**Comment by jochen24** [comment]
Yes, this is correct.
I tested it via adb shell on my device.
I have written 0 or 1 with echo into the file.
This causes stop charging, but device still recognizes connected to power source.

Am 21. Dezember 2017 11:59:53 MEZ schrieb milux <notifications@github.com>:
>What flags cause the desired change? I assume those:
>1 = charging on
>0 = charging off
>Is that correct?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sriharshaarangi/BatteryChargeLimit/issues/73#issuecomment-353322640

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by milux** [comment]
@jochen24 Can you please check out version 1.1.0 and report if it's working?

**Comment by jochen24** [comment]
Hi, I tested it last night and it's working well for my MI A1 with android Oreo. 
Thank you!
