### ISSUE TITLE
Support for Samsung Galaxy S3 (i9300)

### ISSUE THREAD

**Issue by Mibo5354** [sriharshaarangi/BatteryChargeLimit#74]
Samsung S3 i9300 with LOS 14.1-20171213-NIGHTLY
  "file": "/sys/class/power_supply/battery/batt_slate_mode",
  "label": "batt_slate_mode",
  "details": "Samsung GT-I9300",
  "chargeOn": "0",
  "chargeOff": "1"

**Comment by milux** [comment]
I don't get why you opened this... this file is already supported since the early 0.x versions, isn't it?

**Comment by Mibo5354** [comment]
It's just using the wrong file by default

**Comment by milux** [comment]
OK, so you have to select the right one in the settings, what's the matter? :wink:
