### ISSUE TITLE
Feature Request: support Android 4.3

### ISSUE THREAD

**Issue by vovodroid** [sriharshaarangi/BatteryChargeLimit#8]
Any chance to support Android 4.3 (Specifically Samsung Galaxy S3)?

**Comment by milux** [comment]
Please try the following experimental debug build and report back if it works and whether you observed any bugs:
https://www.androidfilehost.com/?fid=817550096634772945

**Comment by vovodroid** [comment]
It seems to work without problems, thanks!

**Comment by vovodroid** [comment]
Probably it's worth to rename topic on xda-developers and edit first post to reflect support of 4.3

**Comment by milux** [comment]
Yes, we will correct that to 4.2.x, which is the new minimum SDK level.
Please wait until the next release and feel free to use the debug build meanwhile.
