### ISSUE TITLE
Doesn't work with ZenFone 2 Laser

### ISSUE THREAD

**Issue by tormentedmage** [sriharshaarangi/BatteryChargeLimit#94]
At first,I tried the following solution to disable charging a battery but it didn't work.
I think your app is basically same as this solution and that's why the app doesn't work with my phone ZenFone 2 Laser(ZE500KL).
Please tell me if you know how I can disable charging my phone with the app.

1. Open any root file manager
2. Connect your mobile to the charger/USB
3. Open the following file: /sys/class/power_supply/battery/charging_enabled (It should be 1 by default)
4. Make it 0 while connected and save the file.

**Comment by milux** [comment]
I don't, and presumable neither do the other team members.
It seems to be a device specific incompatibility, so there's nothing we can do.
See if there is another control file available in settings that you can try out, or look around for the "right file" on your device.
